name: contrastive-unpaired-translation
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.4.0
- scipy
- pip
- pip:
  - dominate==2.6.0
  - torchvision==0.5.0
  - Pillow==7.2.0
  - numpy==1.19.2
  - visdom==0.1.8
  - packaging
  - GPUtil==1.4.0
  - face-alignment==1.1.1
